import {Dimensions, StyleSheet} from 'react-native';
import {scale} from '~/utils/scaling';
import {Colors} from '../../theme/theme';

const {height} = Dimensions.get('window');

export default StyleSheet.create({
  gradientBackground: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  content: {
    paddingHorizontal: scale(16),
    paddingTop: height * 0.08,
  },
  userHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    padding: scale(14),
    borderRadius: scale(12),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    marginBottom: scale(18),
  },
  userAvatar: {
    width: scale(60),
    height: scale(60),
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(14),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  avatar: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
  },
  userName: {
    fontSize: scale(16),
    fontWeight: '700',
    color: '#fff',
  },
  userAddress: {
    fontSize: scale(12),
    color: '#94a3b8',
    marginTop: 6,
  },
  particle1: {
    position: 'absolute',
    top: height * 0.12,
    left: 30,
  },
  particle2: {
    position: 'absolute',
    top: height * 0.2,
    right: 40,
  },
  particle3: {
    position: 'absolute',
    bottom: height * 0.15,
    left: 50,
  },
  particle4: {
    position: 'absolute',
    top: height * 0.35,
    right: 25,
  },
  particleGradient: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoSection: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: scale(25),
    position: 'relative',
  },
  logoBackground: {
    shadowColor: '#764ba2',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.5,
    shadowRadius: 25,
    elevation: 15,
  },
  logoGradient: {
    width: 90,
    height: 90,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoRing: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: 'rgba(167, 139, 250, 0.3)',
  },
  logoRingOuter: {
    width: 130,
    height: 130,
    borderRadius: 70,
    borderWidth: 1,
    borderColor: 'rgba(167, 139, 250, 0.15)',
  },
  title: {
    fontSize: scale(28),
    fontWeight: '800',
    color: '#fff',
    marginBottom: scale(8),
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: scale(14),
    color: '#94a3b8',
    textAlign: 'center',
    paddingHorizontal: scale(30),
    marginBottom: scale(30),
    lineHeight: scale(20),
  },
  featuresContainer: {
    width: '100%',
    marginBottom: scale(25),
  },
  featureCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.deepBackground,
    borderRadius: scale(16),
    padding: scale(16),
    marginBottom: scale(12),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  featureIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(102, 126, 234, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(15),
  },
  featureContent: {
    flex: 1,
  },
  featureTitle: {
    fontSize: scale(15),
    fontWeight: '700',
    color: '#e2e8f0',
    marginBottom: scale(3),
  },
  featureDescription: {
    fontSize: scale(12),
    color: '#94a3b8',
  },
  connectButtonContainer: {
    width: '100%',
    marginBottom: scale(15),
  },
  supportedSection: {
    alignItems: 'center',
  },
  supportedTitle: {
    fontSize: scale(12),
    color: '#64748b',
    marginBottom: scale(12),
    fontWeight: '600',
  },
  walletIcons: {
    flexDirection: 'row',
    gap: scale(10),
  },
  walletIconBox: {
    width: 45,
    height: 45,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  connectedContainer: {
    width: '100%',
    marginTop: scale(20),
  },
  connectedGradient: {
    borderRadius: scale(20),
    padding: scale(20),
    backgroundColor: Colors.deepBackground,
    borderRadius: scale(16),
    marginBottom: scale(12),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  successIconContainer: {
    alignItems: 'center',
    marginBottom: scale(20),
  },
  successIcon: {
    width: 70,
    height: 70,
    borderRadius: 35,
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectedTitle: {
    fontSize: scale(20),
    fontWeight: '700',
    color: '#10b981',
    textAlign: 'center',
    marginBottom: scale(20),
  },
  infoCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: scale(14),
    padding: scale(16),
    marginBottom: scale(12),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scale(10),
  },
  infoLabel: {
    fontSize: scale(13),
    color: '#94a3b8',
    marginLeft: scale(8),
    fontWeight: '600',
  },
  addressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(167, 139, 250, 0.1)',
    padding: scale(12),
    borderRadius: scale(10),
    marginBottom: scale(8),
  },
  addressText: {
    fontSize: scale(16),
    fontWeight: '700',
    color: '#a78bfa',
    letterSpacing: 0.5,
  },
  copyButton: {
    padding: scale(6),
  },
  balanceAmount: {
    fontSize: scale(24),
    fontWeight: '800',
    color: '#fff',
  },
  chainText: {
    fontSize: scale(16),
    fontWeight: '600',
    color: '#fff',
  },
  actionButton: {
    overflow: 'hidden',
    borderRadius: scale(12),
  },
  actionButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scale(14),
    gap: scale(8),
  },
  actionButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: scale(15),
  },
});
