import {StyleSheet, Dimensions} from 'react-native';
import {Colors, FontSizes, FontWeights} from '~/theme/theme';
import {scale} from '~/utils/scaling';

const {width} = Dimensions.get('window');

export default StyleSheet.create({
  gradientBackground: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollContent: {
    paddingBottom: scale(40),
  },
  imageContainer: {
    width: '100%',
    height: scale(380),
    backgroundColor: Colors.deepBackground,
  },
  nftImage: {
    width: '100%',
    height: '100%',
  },
  content: {
    paddingHorizontal: scale(16),
    paddingTop: scale(20),
  },
  collectionLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    marginBottom: scale(12),
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    alignSelf: 'flex-start',
    paddingHorizontal: scale(12),
    paddingVertical: scale(6),
    borderRadius: scale(20),
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.3)',
  },
  collectionText: {
    color: Colors.primary,
    fontSize: FontSizes.small,
    fontWeight: FontWeights.semiBold,
  },
  title: {
    color: Colors.white,
    fontSize: scale(28),
    fontWeight: FontWeights.bold,
    marginBottom: scale(16),
    lineHeight: scale(34),
  },
  priceSection: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: scale(16),
    padding: scale(20),
    marginBottom: scale(20),
  },
  priceLabel: {
    color: Colors.textGray,
    fontSize: FontSizes.small,
    marginBottom: scale(8),
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  price: {
    color: Colors.white,
    fontSize: scale(32),
    fontWeight: FontWeights.bold,
  },
  actionButtons: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    gap: scale(12),
    padding: scale(16),
    backgroundColor: 'rgba(17, 24, 39, 0.95)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  buyButton: {
    flex: 1,
    borderRadius: scale(12),
  },
  offerButton: {
    flex: 1,
    borderRadius: scale(12),
    borderWidth: 2,
    borderColor: Colors.primary,
    backgroundColor: 'transparent',
  },
  offerButtonText: {
    color: Colors.primary,
  },
  userSection: {
    marginBottom: scale(16),
  },
  sectionHeaderUser: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
    marginBottom: scale(12),
  },
  sectionLabel: {
    color: Colors.textGray,
    fontSize: FontSizes.small,
    fontWeight: FontWeights.medium,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  userRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(12),
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    padding: scale(12),
    borderRadius: scale(12),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  avatarContainer: {
    position: 'relative',
    width: scale(48),
    height: scale(48),
  },
  avatarLarge: {
    width: '100%',
    height: '100%',
    borderRadius: scale(24),
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  checkBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: Colors.accent,
    borderRadius: 999,
    padding: scale(4),
    borderWidth: 2,
    borderColor: Colors.deepBackground,
  },
  checkIcon: {
    color: Colors.white,
    width: scale(10),
    height: scale(10),
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    color: Colors.white,
    fontSize: FontSizes.medium,
    fontWeight: FontWeights.semiBold,
    marginBottom: scale(4),
  },
  userAddress: {
    color: Colors.textGray,
    fontSize: FontSizes.small,
  },
  section: {
    marginTop: scale(24),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: scale(16),
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  sectionTitle: {
    color: Colors.white,
    fontSize: FontSizes.large,
    fontWeight: FontWeights.bold,
  },
  sectionContent: {
    paddingTop: scale(16),
  },
  description: {
    color: Colors.textGray,
    fontSize: FontSizes.medium,
    lineHeight: scale(24),
  },
  propertiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scale(12),
    marginTop: scale(16),
  },
  propertyCard: {
    width: (width - scale(44.5)) / 2,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: scale(12),
    padding: scale(16),
  },
  propertyTrait: {
    color: Colors.primary,
    fontSize: FontSizes.xsmall,
    fontWeight: FontWeights.semiBold,
    textTransform: 'uppercase',
    marginBottom: scale(6),
    letterSpacing: 0.5,
  },
  propertyValue: {
    color: Colors.white,
    fontSize: FontSizes.medium,
    fontWeight: FontWeights.bold,
    marginBottom: scale(4),
  },
  propertyRarity: {
    color: Colors.textGray,
    fontSize: FontSizes.xsmall,
  },
  detailsList: {
    gap: scale(12),
  },
  detailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: scale(12),
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  detailLabel: {
    color: Colors.textGray,
    fontSize: FontSizes.small,
    textTransform: 'capitalize',
  },
  detailValue: {
    color: Colors.white,
    fontSize: FontSizes.small,
    fontWeight: FontWeights.semiBold,
    maxWidth: '60%',
    textAlign: 'right',
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: scale(12),
    padding: scale(16),
    gap: scale(12),
    marginBottom: scale(12),
  },
  activityIcon: {
    width: scale(44),
    height: scale(44),
    borderRadius: scale(22),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.3)',
  },
  activityContent: {
    flex: 1,
  },
  activityType: {
    color: Colors.white,
    fontSize: FontSizes.medium,
    fontWeight: FontWeights.semiBold,
    marginBottom: scale(4),
  },
  activityDetails: {
    color: Colors.textGray,
    fontSize: FontSizes.small,
    lineHeight: scale(18),
  },
  productTitle: {
    color: Colors.white,
    fontSize: FontSizes.semiLarge,
    fontWeight: FontWeights.extraBold,
    letterSpacing: 1,
    marginBottom: scale(10),
  },
});
