import {StyleSheet} from 'react-native';
import {Colors, FontSizes, FontWeights} from '~/theme/theme';
import {scale} from '~/utils/scaling';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    paddingBottom: scale(40),
  },
  content: {
    paddingHorizontal: scale(16),
    paddingTop: scale(24),
  },
  uploadSection: {
    backgroundColor: Colors.deepBackground,
    borderWidth: 2,
    borderColor: Colors.border,
    borderStyle: 'dashed',
    borderRadius: scale(12),
    padding: scale(32),
    alignItems: 'center',
    marginBottom: scale(32),
    minHeight: scale(280),
    justifyContent: 'center',
  },
  uploadIcon: {
    width: scale(80),
    height: scale(80),
    backgroundColor: 'rgba(0,217,255,0.1)',
    borderRadius: scale(40),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: scale(16),
  },
  uploadTitle: {
    color: Colors.white,
    fontSize: FontSizes.regular,
    fontWeight: FontWeights.semiBold,
    marginBottom: scale(4),
  },
  uploadSubtitle: {
    color: Colors.textHighlight,
    fontSize: FontSizes.small,
    marginBottom: scale(16),
  },
  imagePreviewContainer: {
    width: '100%',
    borderRadius: scale(12),
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.deepBackground,
    minHeight: scale(250),
  },
  previewImage: {
    width: '100%',
    height: scale(250),
    borderRadius: scale(12),
  },
  removeImageButton: {
    position: 'absolute',
    top: scale(8),
    right: scale(8),
    zIndex: 10,
    backgroundColor: Colors.redColor,
    width: scale(28),
    height: scale(28),
    borderRadius: scale(14),
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageWrapper: {
    width: '100%',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewImageWrapper: {
    gap: scale(6),
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  uploadedImageSize: {
    color: Colors.textHighlight,
    fontSize: FontSizes.small,
  },
  supportedFormats: {
    marginBottom: scale(20),
  },
  supportedFormatsText: {
    color: Colors.textHighlight,
    fontSize: FontSizes.small,
    lineHeight: 20,
    textAlign: 'center',
  },
  uploadedImageContainer: {
    alignItems: 'center',
  },
  uploadedImageText: {
    color: Colors.primary,
    fontSize: FontSizes.regular,
    fontWeight: FontWeights.semiBold,
    marginBottom: scale(8),
  },
  section: {
    marginBottom: scale(10),
  },
  sectionHeader: {
    marginBottom: scale(12),
  },
  formGroup: {
    marginBottom: scale(24),
  },
  label: {
    color: Colors.white,
    fontSize: scale(14),
    fontWeight: FontWeights.semiBold,
    marginBottom: scale(8),
  },
  inputContainer: {
    marginBottom: scale(8),
  },
  textArea: {
    minHeight: scale(120),
    color: Colors.white,
    fontSize: FontSizes.small,
  },
  hint: {
    color: Colors.textHighlight,
    fontSize: FontSizes.small,
    lineHeight: 22,
  },
  propertyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
    marginBottom: scale(12),
  },
  propertyInput: {
    width: scale(138),
    marginBottom: 0,
  },
  removeButton: {
    width: scale(52),
    height: scale(52),
    backgroundColor: 'rgba(255,0,107,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,0,107,0.3)',
    borderRadius: scale(8),
    justifyContent: 'center',
    alignItems: 'center',
  },
  dropdownButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.deepBackground,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: scale(8),
    paddingVertical: scale(14),
    paddingHorizontal: scale(16),
    marginBottom: scale(8),
  },
  dropdownText: {
    color: Colors.white,
    fontSize: FontSizes.small,
    fontWeight: FontWeights.medium,
  },
  dropdownListAbsolute: {
    position: 'absolute',
    top: scale(52),
    left: 0,
    right: 0,
    backgroundColor: Colors.deepBackground,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: scale(8),
    zIndex: 999,
    elevation: 5,
  },
  dropdownItem: {
    gap: scale(6),
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: scale(12),
    paddingHorizontal: scale(16),
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  dropdownItemActive: {
    backgroundColor: 'rgba(0,217,255,0.1)',
  },
  dropdownItemText: {
    color: Colors.textGray,
    fontSize: FontSizes.small,
  },
  dropdownItemTextActive: {
    color: Colors.primary,
    fontWeight: FontWeights.bold,
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.deepBackground,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: scale(8),
    padding: scale(16),
    marginBottom: scale(6),
  },
  switchLabel: {
    flex: 1,
    marginRight: scale(16),
  },
  buttonContainer: {
    padding: scale(16),
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  errorText: {
    color: Colors.redColor,
    fontSize: FontSizes.small,
    fontWeight: FontWeights.medium,
    marginTop: scale(4),
  },
});
